### CarrinhosController
@url = http://localhost:5295/api/carrinhos

# Consultar itens no carrinho do usuário
GET {{url}}/2
Accept: application/json

###

# Consultar apenas um item do carrinho do usuário
GET {{url}}/2/10
Accept: application/json

###

# Adicionar um novo item no carrinho
POST {{url}}/2
Content-Type: application/json
Accept: application/json

{
  "jogoId": 3,
  "quantidade": 1
}

###

# Atualizar a quantidade de um item do carrinho
PATCH {{url}}/2/10
Content-Type: application/json
Accept: application/json

{
  "quantidade": 3
}

###

# Remover um item do carrinho
DELETE {{url}}/2/7
Content-Type: application/json
Accept: application/json
