// <auto-generated />
using System;
using FIAP.FCG.Infrastructure.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FIAP.FCG.Domain.FIAP.FCG.Infrastructure.Dados.Migracoes
{
    [DbContext(typeof(ContextoBancoDadosFCG))]
    [Migration("20260418132456_InicializacaoDeBancoExistente")]
    partial class InicializacaoDeBancoExistente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FIAP.FCG.Web.API.Acesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dataHora")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioId");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UsuarioId", "DataHora" }, "IX_Acessos_UsuarioId_DataHora")
                        .IsDescending(false, true);

                    b.ToTable("Acessos");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.Administradore", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioId");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("UsuarioId");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.Carrinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("JogoId")
                        .HasColumnType("int")
                        .HasColumnName("jogoId");

                    b.Property<short>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("quantidade");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioId");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex(new[] { "UsuarioId" }, "IX_Carrinhos_UsuarioId");

                    b.HasIndex(new[] { "UsuarioId", "JogoId" }, "UQ_Carrinhos_Usr_Jogo")
                        .IsUnique();

                    b.ToTable("Carrinhos");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Nome" }, "UQ_Categorias_Nome")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.IntegradorasPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Nome" }, "UQ_IntegradorasPagamento_Nome")
                        .IsUnique();

                    b.ToTable("IntegradorasPagamento", (string)null);
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("categoriaId");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateOnly?>("DataLancamento")
                        .HasColumnType("date")
                        .HasColumnName("dataLancamento");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nome");

                    b.Property<bool>("Visivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("visivel");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CategoriaId" }, "IX_Jogos_CategoriaId");

                    b.HasIndex(new[] { "Nome" }, "IX_Jogos_Nome");

                    b.HasIndex(new[] { "Visivel", "Ativo" }, "IX_Jogos_Visivel_Ativo");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.JogosAdquirido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JogoId")
                        .HasColumnType("int")
                        .HasColumnName("jogoId");

                    b.Property<short>("Quantidade")
                        .HasColumnType("smallint")
                        .HasColumnName("quantidade");

                    b.Property<int>("TransacaoId")
                        .HasColumnType("int")
                        .HasColumnName("transacaoId");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioId");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("valorTotal");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("valorUnitario");

                    b.HasKey("Id");

                    b.HasIndex("TransacaoId");

                    b.HasIndex(new[] { "JogoId" }, "IX_JogosAdquiridos_JogoId");

                    b.HasIndex(new[] { "UsuarioId" }, "IX_JogosAdquiridos_UsuarioId");

                    b.HasIndex(new[] { "UsuarioId", "JogoId" }, "UQ_JogosAdquiridos_Usr_Jogo")
                        .IsUnique();

                    b.ToTable("JogosAdquiridos");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.PrecosJogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataInicio");

                    b.Property<int>("JogoId")
                        .HasColumnType("int")
                        .HasColumnName("jogoId");

                    b.Property<decimal?>("PercDesconto")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("percDesconto");

                    b.Property<int?>("PromocaoId")
                        .HasColumnType("int")
                        .HasColumnName("promocaoId");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("PromocaoId");

                    b.HasIndex(new[] { "JogoId", "DataInicio" }, "IX_PrecosJogos_JogoId_DataInicio")
                        .IsDescending(false, true);

                    b.ToTable("PrecosJogos");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.Promoco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataFim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataInicio");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PercDesconto")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("percDesconto");

                    b.HasKey("Id");

                    b.ToTable("Promocoes");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descricao");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("endereco");

                    b.Property<int>("JogoId")
                        .HasColumnType("int")
                        .HasColumnName("jogoId");

                    b.Property<string>("TipoResource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipoResource");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "JogoId", "TipoResource" }, "IX_Resources_JogoId_Tipo");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Nome" }, "UQ_Tags_Nome")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.Transaco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comprovante")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("comprovante");

                    b.Property<DateTime>("DataCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCompra")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("IntegradoraPagamentoId")
                        .HasColumnType("int")
                        .HasColumnName("integradoraPagamentoId");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("valorTotal");

                    b.HasKey("Id");

                    b.HasIndex("IntegradoraPagamentoId");

                    b.HasIndex(new[] { "Comprovante" }, "IX_Transacoes_Comprovante");

                    b.HasIndex(new[] { "DataCompra" }, "IX_Transacoes_DataCompra")
                        .IsDescending();

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("hashSenha");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nomeUsuario");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Ativo" }, "IX_Usuarios_Ativo");

                    b.HasIndex(new[] { "Email" }, "IX_Usuarios_Email");

                    b.HasIndex(new[] { "Email" }, "UQ_Usuarios_Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ListasDeDesejo", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<int>("IdJogo")
                        .HasColumnType("int")
                        .HasColumnName("idJogo");

                    b.HasKey("IdUsuario", "IdJogo");

                    b.HasIndex(new[] { "IdJogo" }, "IX_ListasDeDesejos_IdJogo");

                    b.ToTable("ListasDeDesejos", (string)null);
                });

            modelBuilder.Entity("TagsPorJogo", b =>
                {
                    b.Property<int>("IdJogo")
                        .HasColumnType("int")
                        .HasColumnName("idJogo");

                    b.Property<int>("IdTag")
                        .HasColumnType("int")
                        .HasColumnName("idTag");

                    b.HasKey("IdJogo", "IdTag");

                    b.HasIndex(new[] { "IdTag" }, "IX_TagsPorJogo_IdTag");

                    b.ToTable("TagsPorJogo", (string)null);
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.Acesso", b =>
                {
                    b.HasOne("FIAP.FCG.Web.API.Usuario", "Usuario")
                        .WithMany("Acessos")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Acessos_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.Administradore", b =>
                {
                    b.HasOne("FIAP.FCG.Web.API.Usuario", "Usuario")
                        .WithOne("Administradore")
                        .HasForeignKey("FIAP.FCG.Web.API.Administradore", "UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Administradores_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.Carrinho", b =>
                {
                    b.HasOne("FIAP.FCG.Web.API.Jogo", "Jogo")
                        .WithMany("Carrinhos")
                        .HasForeignKey("JogoId")
                        .IsRequired()
                        .HasConstraintName("FK_Carrinhos_Jogos");

                    b.HasOne("FIAP.FCG.Web.API.Usuario", "Usuario")
                        .WithMany("Carrinhos")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Carrinhos_Usuarios");

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.Jogo", b =>
                {
                    b.HasOne("FIAP.FCG.Web.API.Categoria", "Categoria")
                        .WithMany("Jogos")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK_Jogos_Categorias");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.JogosAdquirido", b =>
                {
                    b.HasOne("FIAP.FCG.Web.API.Jogo", "Jogo")
                        .WithMany("JogosAdquiridos")
                        .HasForeignKey("JogoId")
                        .IsRequired()
                        .HasConstraintName("FK_JogosAdquiridos_Jogos");

                    b.HasOne("FIAP.FCG.Web.API.Transaco", "Transacao")
                        .WithMany("JogosAdquiridos")
                        .HasForeignKey("TransacaoId")
                        .IsRequired()
                        .HasConstraintName("FK_JogosAdquiridos_Transacoes");

                    b.HasOne("FIAP.FCG.Web.API.Usuario", "Usuario")
                        .WithMany("JogosAdquiridos")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_JogosAdquiridos_Usuarios");

                    b.Navigation("Jogo");

                    b.Navigation("Transacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.PrecosJogo", b =>
                {
                    b.HasOne("FIAP.FCG.Web.API.Jogo", "Jogo")
                        .WithMany("PrecosJogos")
                        .HasForeignKey("JogoId")
                        .IsRequired()
                        .HasConstraintName("FK_PrecosJogos_Jogos");

                    b.HasOne("FIAP.FCG.Web.API.Promoco", "Promocao")
                        .WithMany("PrecosJogos")
                        .HasForeignKey("PromocaoId")
                        .HasConstraintName("FK_PrecosJogos_Promocoes");

                    b.Navigation("Jogo");

                    b.Navigation("Promocao");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.Resource", b =>
                {
                    b.HasOne("FIAP.FCG.Web.API.Jogo", "Jogo")
                        .WithMany("Resources")
                        .HasForeignKey("JogoId")
                        .IsRequired()
                        .HasConstraintName("FK_Resources_Jogos");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.Transaco", b =>
                {
                    b.HasOne("FIAP.FCG.Web.API.IntegradorasPagamento", "IntegradoraPagamento")
                        .WithMany("Transacos")
                        .HasForeignKey("IntegradoraPagamentoId")
                        .IsRequired()
                        .HasConstraintName("FK_Transacoes_IntegradorasPagamento");

                    b.Navigation("IntegradoraPagamento");
                });

            modelBuilder.Entity("ListasDeDesejo", b =>
                {
                    b.HasOne("FIAP.FCG.Web.API.Jogo", null)
                        .WithMany()
                        .HasForeignKey("IdJogo")
                        .IsRequired()
                        .HasConstraintName("FK_ListasDeDesejos_Jogos");

                    b.HasOne("FIAP.FCG.Web.API.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_ListasDeDesejos_Usuarios");
                });

            modelBuilder.Entity("TagsPorJogo", b =>
                {
                    b.HasOne("FIAP.FCG.Web.API.Jogo", null)
                        .WithMany()
                        .HasForeignKey("IdJogo")
                        .IsRequired()
                        .HasConstraintName("FK_TagsPorJogo_Jogos");

                    b.HasOne("FIAP.FCG.Web.API.Tag", null)
                        .WithMany()
                        .HasForeignKey("IdTag")
                        .IsRequired()
                        .HasConstraintName("FK_TagsPorJogo_Tags");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.Categoria", b =>
                {
                    b.Navigation("Jogos");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.IntegradorasPagamento", b =>
                {
                    b.Navigation("Transacos");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.Jogo", b =>
                {
                    b.Navigation("Carrinhos");

                    b.Navigation("JogosAdquiridos");

                    b.Navigation("PrecosJogos");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.Promoco", b =>
                {
                    b.Navigation("PrecosJogos");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.Transaco", b =>
                {
                    b.Navigation("JogosAdquiridos");
                });

            modelBuilder.Entity("FIAP.FCG.Web.API.Usuario", b =>
                {
                    b.Navigation("Acessos");

                    b.Navigation("Administradore");

                    b.Navigation("Carrinhos");

                    b.Navigation("JogosAdquiridos");
                });
#pragma warning restore 612, 618
        }
    }
}
