version: "3.8"

services:
  data:
    build:
      dockerfile: DockerSqlServer/linux.Dockerfile
      context: ..
    container_name: fcg-data
    volumes:
      - fcg-sqlserver-data:/var/opt/mssql
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'woeIr34@#sjk'
    ports:
      - "1400:1433"
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  fcg-sqlserver-data:
